#!/usr/bin/env node
// Reads MITEMC's JSON recipes and emits a markdown table summarizing them.
// Usage:  node scripts/render-recipes.mjs > wiki/src/content/docs/_recipe-table.md
// Or:     node scripts/render-recipes.mjs --json   to emit machine-readable JSON.

import { readdirSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const repoRoot = new URL('..', import.meta.url).pathname.replace(/\/$/, '');
const RECIPES_DIR = join(repoRoot, 'mod/src/main/resources/data/mitemc/recipes');

if (!existsSync(RECIPES_DIR)) {
  console.error(`No recipes dir at ${RECIPES_DIR}`);
  process.exit(2);
}

const files = readdirSync(RECIPES_DIR).filter(f => f.endsWith('.json'));
const recipes = [];

for (const file of files) {
  const path = join(RECIPES_DIR, file);
  const json = JSON.parse(readFileSync(path, 'utf8'));
  const id = file.replace(/\.json$/, '');
  const type = json.type ?? 'unknown';

  let inputs = [];
  let result = null;
  let count = 1;

  if (type === 'minecraft:crafting_shaped') {
    const flat = (json.pattern ?? []).join('').replace(/ /g, '');
    const keys = Object.entries(json.key ?? {});
    inputs = keys.map(([k, v]) => `${prettyIngredient(v)} ×${(flat.match(new RegExp(k, 'g')) || []).length}`);
    result = json.result?.id ?? json.result?.item;
    count  = json.result?.count ?? 1;
  } else if (type === 'minecraft:crafting_shapeless') {
    inputs = (json.ingredients ?? []).map(prettyIngredient);
    result = json.result?.id ?? json.result?.item;
    count  = json.result?.count ?? 1;
  } else if (type === 'minecraft:smelting' || type === 'minecraft:blasting') {
    inputs = [prettyIngredient(json.ingredient)];
    result = json.result?.id ?? json.result?.item;
    count  = 1;
    inputs.push(`(${json.cookingtime ?? '?'} t, ${json.experience ?? 0} XP)`);
  } else {
    inputs = ['(unsupported recipe type)'];
    result = '?';
  }

  recipes.push({ id, type, inputs, result, count });
}

if (process.argv.includes('--json')) {
  console.log(JSON.stringify(recipes, null, 2));
  process.exit(0);
}

// Markdown output
recipes.sort((a, b) => a.type.localeCompare(b.type) || a.id.localeCompare(b.id));

console.log('<!-- AUTO-GENERATED by scripts/render-recipes.mjs — do not edit by hand -->');
console.log('');
console.log('| Recipe ID | Type | Inputs | Result | Count |');
console.log('|-----------|------|--------|--------|------:|');
for (const r of recipes) {
  console.log(`| \`${r.id}\` | ${shortType(r.type)} | ${r.inputs.join(', ')} | \`${r.result ?? '?'}\` | ${r.count} |`);
}
console.log('');
console.log(`<!-- ${recipes.length} recipes total -->`);

function prettyIngredient(ing) {
  if (!ing) return '?';
  if (Array.isArray(ing)) return ing.map(prettyIngredient).join(' or ');
  if (typeof ing === 'object') {
    if (ing.item) return `\`${ing.item}\``;
    if (ing.tag)  return `\`#${ing.tag}\``;
  }
  return String(ing);
}

function shortType(t) {
  if (t === 'minecraft:crafting_shaped')    return 'shaped';
  if (t === 'minecraft:crafting_shapeless') return 'shapeless';
  if (t === 'minecraft:smelting')           return 'smelt';
  if (t === 'minecraft:blasting')           return 'blast';
  return t;
}
